### ISSUE TITLE
请问不支持chrome肿么办？

### ISSUE THREAD

**Issue by erikaemma** [HFIProgramming/mikutap#1]
原网站在chrome下是好用的，并且还支持屏蔽输入法。
而您的这个我只能在edge下使用，还和官网一样在edge下不能屏蔽输入法。
在chrome下，点开始，网页一条白线，没有缩短，就不动了。

**Comment by NeverBehave** [comment]
项目介绍里面的录屏就是用的chrome，是完美支持的。
请自行检查网络，或提供更多信息
