### ISSUE TITLE
https://github.com/HFIProgramming/mikutap/tree/master/data/track

### ISSUE THREAD

**Issue by loadingfd** [HFIProgramming/mikutap#12]
https://github.com/HFIProgramming/mikutap/tree/master/data/track

_Originally posted by @NeverBehave in https://github.com/HFIProgramming/mikutap/issues/11#issuecomment-647632855_

并非如此，json是背景音源，我想问的是miku的音源在哪里

**Comment by liuxilu** [comment]
干嘛新issue+奇怪的标题。举一反三得 https://github.com/HFIProgramming/mikutap/blob/master/data/main/main.json

**Comment by loadingfd** [comment]
> 干嘛新issue+奇怪的标题。举一反三得 https://github.com/HFIProgramming/mikutap/blob/master/data/main/main.json

抱歉，自己没找到
