### ISSUE TITLE
求助，

### ISSUE THREAD

**Issue by 0000070** [HFIProgramming/mikutap#13]
不管是放在本地还是虚拟主机里面开始游戏都会提示：jquery.min.js:4 Access to XMLHttpRequest at 'file:///D:/11152/data/track/track.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, weapp, https.
网站是有https的，本地文件夹也是全英文的，这种情况怎么解决呢 
![image](https://user-images.githubusercontent.com/36756720/85966069-4be86600-b9f1-11ea-8def-65db8c84a204.png)

**Comment by NeverBehave** [comment]
https://github.com/HFIProgramming/mikutap/issues/6
