### ISSUE TITLE
please add a license

### ISSUE THREAD

**Issue by hehelego** [HFIProgramming/mikutap#14]

**Comment by NeverBehave** [comment]
This project’s copyright belongs to aidn.jp , and the project readme has mentioned about how it works: https://github.com/HFIProgramming/mikutap#%E7%89%88%E6%9D%83%E8%AF%B4%E6%98%8E

You may use it free for non-commercial usage. For commercial usage, email daniwell@aidn.jp for more info.

> Someone said this statement is used for his songs. With that being said, you should send email no matter how you use it.
