### ISSUE TITLE
这个音乐是如何播放的呢

### ISSUE THREAD

**Issue by chenrui520** [HFIProgramming/mikutap#5]
![image](https://user-images.githubusercontent.com/33218134/59145685-e4dcc580-8a19-11e9-919a-4b8df2a87a0d.png)
我把音乐循环播放发现不对呀。没看懂，求教

**Comment by NeverBehave** [comment]
被进行压缩后的源码恕不进行分析

**Comment by chenrui520** [comment]
是直接搬运的吗。。。
