### ISSUE TITLE
为什么在本地无法使用？

### ISSUE THREAD

**Issue by yuyulangqi** [HFIProgramming/mikutap#6]
![image](https://user-images.githubusercontent.com/44050395/59268666-cbd54e00-8c7f-11e9-8e43-09893fd3f96c.png)
![Uploading image.png…]()
请大神指教一下

**Comment by yuyulangqi** [comment]
用Chrome一直卡在这个界面
![image](https://user-images.githubusercontent.com/44050395/59269195-17d4c280-8c81-11e9-8c77-650c1873ca81.png)
用edge就正常
![image](https://user-images.githubusercontent.com/44050395/59269262-3c309f00-8c81-11e9-9d22-44c761a5fe4f.png)

**Comment by NeverBehave** [comment]
...本地开Chrome有安全限制

**Comment by yuyulangqi** [comment]
有什么解决办法吗？

**Comment by NeverBehave** [comment]
> 有什么解决办法吗？

别在本地，或者是自己调整一下路径不要用xhr获取音乐文件

**Comment by yuyulangqi** [comment]
已经解决了，部署到服务器就行了
