### ISSUE TITLE
pixi.js的CDN源挂掉了

### ISSUE THREAD

**Issue by Leslie-Wong-H** [HFIProgramming/mikutap#8]
![image](https://user-images.githubusercontent.com/27696701/62322292-50ea2000-b4d7-11e9-9c86-6ea5731abd2a.png)

发现大家的这网页都运行不了了
https://www.lesliewong.cn/music/music.html
https://blog.eunji.cn/music/music.html

**Comment by NeverBehave** [comment]
无法复现

**Comment by NeverBehave** [comment]
顺带一提：原作者信息就这么碍眼一定要变成你自己？

**Comment by Leslie-Wong-H** [comment]
只是写篇文章推广一下并讲如何个性化部署到自己个人博客域名下而已，全文一直都没提到原作者是自己啊？

https://segmentfault.com/a/1190000017934781

也没有过什么商业盈利之心——

**Comment by Leslie-Wong-H** [comment]
发现原作者的pixi.js的cloudflare源也挂掉了——

**Comment by NeverBehave** [comment]
> 只是写篇文章推广一下并讲如何个性化部署到自己个人博客域名下而已，全文一直都没提到原作者是自己啊？
> 
> https://segmentfault.com/a/1190000017934781
> 
> 也没有过什么商业盈利之心——

确实，但是可以的话请你在自定义的时候，不要抹去原作者信息
这是最基本的尊重，谢谢

**Comment by NeverBehave** [comment]
> 发现原作者的pixi.js的cloudflare源也挂掉了——

chrome和Firefox均无法复现，如果可以请你把环境信息全部贴上来
还有，记得关闭所有插件，并在隐私模式下测试

**Comment by Leslie-Wong-H** [comment]
怀疑是自己电脑的问题，跑到机房电脑测试了下，一切正常。回到自己电脑上，发现又正常了，真是奇怪的网络代理~

另外，点了下原作者信息，也在文章评论区里注明了下
（实不相瞒，阁下原先的声明着实有碍美感~）
![image](https://user-images.githubusercontent.com/27696701/62511403-17eadc00-b846-11e9-92b4-a887ed73e9b6.png)

**Comment by NeverBehave** [comment]
> 怀疑是自己电脑的问题，跑到机房电脑测试了下，一切正常。回到自己电脑上，发现又正常了，真是奇怪的网络代理~
> 
> 另外，点了下原作者信息，也在文章评论区里注明了下
> （实不相瞒，阁下原先的声明着实有碍美感~）
> ![image](https://user-images.githubusercontent.com/27696701/62511403-17eadc00-b846-11e9-92b4-a887ed73e9b6.png)

有碍美观并不是移出原作者信息的理由，不过现在也很感谢你能够重新添加上
